version: '2'

services:
   openrct2:
      container_name: openrct2-cli-for-controller
      image: corysanin/openrct2-cli:develop
      ports:
         - 35711:35711
         - 11753:11753
         - 11754:11754/udp
      volumes:
         - ./lib:/home/openrct2/.config/OpenRCT2/plugin/control
         - ./config/openrct2/plugin.store.json:/home/openrct2/.config/OpenRCT2/plugin.store.json
         - ./config/openrct2/config.ini:/home/openrct2/.config/OpenRCT2/config.ini
      command:
         - "host"
         - "https://taunt.bot/rct/scenarios/"
